import os
TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

PAIRS = {
    "BTCUSDT": "XBTUSDT",
    "ETHUSDT": "ETHUSDT",
    "XRPUSDT": "XRPUSDT",
    "DOGEUSDT": "DOGEUSDT",
    "ADAUSDT": "ADAUSDT",
}

INTERVAL = 15


RISK_PCT = 0.0025
STOP_ATR = 0.6
TP_ATR   = 6.0
LOCK_ATR = 2.0
TRAIL_ATR = 1.8
